"""upgrade_to_banking_grade_encryption

Revision ID: 487fb4a9b26c
Revises: 9c5006b61fdf
Create Date: 2026-05-01 20:25:08.705576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487fb4a9b26c'
down_revision: Union[str, Sequence[str], None] = '9c5006b61fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('full_name_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('contacts', sa.Column('nickname_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('contacts', sa.Column('raast_id_encrypted', sa.LargeBinary(), nullable=True))
    op.alter_column('contacts', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('transactions', sa.Column('recipient_name_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('transactions', sa.Column('note_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('phone_number_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('full_name_encrypted', sa.LargeBinary(), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'full_name_encrypted')
    op.drop_column('users', 'phone_number_encrypted')
    op.drop_column('transactions', 'note_encrypted')
    op.drop_column('transactions', 'recipient_name_encrypted')
    op.alter_column('contacts', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('contacts', 'raast_id_encrypted')
    op.drop_column('contacts', 'nickname_encrypted')
    op.drop_column('contacts', 'full_name_encrypted')
    # ### end Alembic commands ###
