"""Add password_hash full_name

Revision ID: 8b4171408110
Revises: a46586721259
Create Date: 2026-03-18 12:40:23.461664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4171408110'
down_revision: Union[str, Sequence[str], None] = 'a46586721259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF NOT EXISTS to safely skip already-applied columns
    op.execute("""
        ALTER TABLE users 
        ADD COLUMN IF NOT EXISTS full_name VARCHAR(200)
    """)
    op.execute("""
        ALTER TABLE users 
        ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255)
    """)
    op.execute("""
        ALTER TABLE users 
        ADD COLUMN IF NOT EXISTS account_number VARCHAR(50)
    """)

    # Backfill existing rows
    op.execute("UPDATE users SET full_name = 'Unknown' WHERE full_name IS NULL")
    op.execute("UPDATE users SET password_hash = '' WHERE password_hash IS NULL")

    # Enforce NOT NULL
    op.alter_column('users', 'full_name', nullable=False)
    op.alter_column('users', 'password_hash', nullable=False)

    # Unique constraint (only add if not already there)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'uq_users_account_number'
            ) THEN
                ALTER TABLE users ADD CONSTRAINT uq_users_account_number UNIQUE (account_number);
            END IF;
        END
        $$;
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'account_number')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
