"""Add password_hash full_name

Revision ID: 8b4171408110
Revises: a46586721259
Create Date: 2026-03-18 12:40:23.461664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4171408110'
down_revision: Union[str, Sequence[str], None] = 'a46586721259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'account_number')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
