"""add encrypted columns to users

Revision ID: f17ea24dd3ce
Revises: 487fb4a9b26c
Create Date: 2026-05-18 13:37:22.543545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17ea24dd3ce'
down_revision: Union[str, Sequence[str], None] = '487fb4a9b26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('voice_nonces',
    sa.Column('nonce', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    # op.alter_column('system_logs', 'partner_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    # op.alter_column('system_logs', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    # op.alter_column('system_logs', 'admin_user_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    # op.alter_column('system_logs', 'reference_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    op.execute('ALTER TABLE system_logs ALTER COLUMN partner_id TYPE UUID USING partner_id::text::uuid')
    op.execute('ALTER TABLE system_logs ALTER COLUMN user_id TYPE UUID USING user_id::text::uuid')
    op.execute('ALTER TABLE system_logs ALTER COLUMN admin_user_id TYPE UUID USING admin_user_id::text::uuid')
    op.execute('ALTER TABLE system_logs ALTER COLUMN reference_id TYPE UUID USING reference_id::text::uuid')
    op.add_column('users', sa.Column('phone_number_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_phone_number_hash'), 'users', ['phone_number_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number_hash'), table_name='users')
    op.drop_column('users', 'phone_number_hash')
    op.alter_column('system_logs', 'reference_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('system_logs', 'admin_user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('system_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('system_logs', 'partner_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_table('voice_nonces')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
